export const StudentDummy = [
  {
    id: 1,
    section: {
      id: 1,
      grade: {
        id: 1,
        name: "Grade 2",
        academic_year: {
          id: 1,
          start_year: 2024,
          end_year: 2025,
          status: "Active",
          created: "2024-02-19",
          school: 1,
        },
        department: {
          id: 1,
          name: "Test Primary Boys",
          campus: {
            id: 1,
            name: "Test Campus Boys",
            branch: {
              id: 1,
              name: "My Test Branch",
              school: {
                id: 1,
                name: "Testing School",
              },
            },
          },
        },
      },
      home_room_teacher: null,
      name: "P2 Sec 1",
      max_no_of_student: 50,
      created: "2024-02-19",
    },
    campus: {
      id: 1,
      name: "Test Campus Boys",
      branch: {
        id: 1,
        name: "My Test Branch",
        school: {
          id: 1,
          name: "Testing School",
        },
      },
    },
    applied_grade: {
      id: 1,
      academic_year: {
        id: 1,
        start_year: 2024,
        end_year: 2025,
        status: "Active",
        created: "2024-02-19",
        school: 1,
      },
      department: {
        id: 1,
        name: "Test Primary Boys",
        campus: {
          id: 1,
          name: "Test Campus Boys",
          branch: {
            id: 1,
            name: "My Test Branch",
            school: {
              id: 1,
              name: "Testing School",
            },
          },
        },
      },
      name: "Grade 2",
      level_number: null,
      grading_criteria: null,
      number_of_sections: null,
      created: "2024-02-19",
    },
    parentData: {
      parent_name_arabic: "parent",
      parent_name_english: "test",
    },
    studentData: {
      student_national_id: "12212121",
      student_first_name_english: "test",
      student_middle_name_english: "student",
      student_last_name_english: "one",
      student_first_name_arabic: "test",
      student_middle_name_arabic: "student",
      student_last_name_arabic: "one",
      student_gender: "Male",
      student_date_of_birth: "2002-02-01",
    },
    status: "Active",
    created_at: "2024-02-19",
    student: 1,
  },
  {
    id: 5,
    section: {
      id: 1,
      grade: {
        id: 1,
        name: "Grade 2",
        academic_year: {
          id: 1,
          start_year: 2024,
          end_year: 2025,
          status: "Active",
          created: "2024-02-19",
          school: 1,
        },
        department: {
          id: 1,
          name: "Test Primary Boys",
          campus: {
            id: 1,
            name: "Test Campus Boys",
            branch: {
              id: 1,
              name: "My Test Branch",
              school: {
                id: 1,
                name: "Testing School",
              },
            },
          },
        },
      },
      home_room_teacher: null,
      name: "P2 Sec 1",
      max_no_of_student: 50,
      created: "2024-02-19",
    },
    campus: {
      id: 1,
      name: "Test Campus Boys",
      branch: {
        id: 1,
        name: "My Test Branch",
        school: {
          id: 1,
          name: "Testing School",
        },
      },
    },
    applied_grade: {
      id: 1,
      academic_year: {
        id: 1,
        start_year: 2024,
        end_year: 2025,
        status: "Active",
        created: "2024-02-19",
        school: 1,
      },
      department: {
        id: 1,
        name: "Test Primary Boys",
        campus: {
          id: 1,
          name: "Test Campus Boys",
          branch: {
            id: 1,
            name: "My Test Branch",
            school: {
              id: 1,
              name: "Testing School",
            },
          },
        },
      },
      name: "Grade 2",
      level_number: null,
      grading_criteria: null,
      number_of_sections: null,
      created: "2024-02-19",
    },
    parentData: {
      parent_name_arabic: "Muhammad Sarwar",
      parent_name_english: "Muhammad Sarwar",
    },
    studentData: {
      student_national_id: "dfsafasdf",
      student_first_name_english: "Ammar",
      student_middle_name_english: "Sarwar",
      student_last_name_english: "Ali",
      student_first_name_arabic: "Ammar",
      student_middle_name_arabic: "Sarwar",
      student_last_name_arabic: "Alu",
      student_gender: "Male",
      student_date_of_birth: "2002-01-22",
    },
    status: "Active",
    created_at: "2024-03-05",
    student: 6,
  },
  {
    id: 7,
    section: {
      id: 1,
      grade: {
        id: 1,
        name: "Grade 2",
        academic_year: {
          id: 1,
          start_year: 2024,
          end_year: 2025,
          status: "Active",
          created: "2024-02-19",
          school: 1,
        },
        department: {
          id: 1,
          name: "Test Primary Boys",
          campus: {
            id: 1,
            name: "Test Campus Boys",
            branch: {
              id: 1,
              name: "My Test Branch",
              school: {
                id: 1,
                name: "Testing School",
              },
            },
          },
        },
      },
      home_room_teacher: null,
      name: "P2 Sec 1",
      max_no_of_student: 50,
      created: "2024-02-19",
    },
    campus: {
      id: 1,
      name: "Test Campus Boys",
      branch: {
        id: 1,
        name: "My Test Branch",
        school: {
          id: 1,
          name: "Testing School",
        },
      },
    },
    applied_grade: {
      id: 1,
      academic_year: {
        id: 1,
        start_year: 2024,
        end_year: 2025,
        status: "Active",
        created: "2024-02-19",
        school: 1,
      },
      department: {
        id: 1,
        name: "Test Primary Boys",
        campus: {
          id: 1,
          name: "Test Campus Boys",
          branch: {
            id: 1,
            name: "My Test Branch",
            school: {
              id: 1,
              name: "Testing School",
            },
          },
        },
      },
      name: "Grade 2",
      level_number: null,
      grading_criteria: null,
      number_of_sections: null,
      created: "2024-02-19",
    },
    parentData: {
      parent_name_arabic: "Muhammad Sarwar shah",
      parent_name_english: "Muhammad Sarwar shah",
    },
    studentData: {
      student_national_id: "2343243",
      student_first_name_english: "Ammar",
      student_middle_name_english: "Sarwar",
      student_last_name_english: "shah",
      student_first_name_arabic: "Ammar",
      student_middle_name_arabic: "Sarwar",
      student_last_name_arabic: "shah",
      student_gender: "Male",
      student_date_of_birth: "2002-01-22",
    },
    status: "Active",
    created_at: "2024-03-05",
    student: 8,
  },
  {
    id: 7,
    section: {
      id: 1,
      grade: {
        id: 1,
        name: "Grade 2",
        academic_year: {
          id: 1,
          start_year: 2024,
          end_year: 2025,
          status: "Active",
          created: "2024-02-19",
          school: 1,
        },
        department: {
          id: 1,
          name: "Test Primary Boys",
          campus: {
            id: 1,
            name: "Test Campus Boys",
            branch: {
              id: 1,
              name: "My Test Branch",
              school: {
                id: 1,
                name: "Testing School",
              },
            },
          },
        },
      },
      home_room_teacher: null,
      name: "P2 Sec 1",
      max_no_of_student: 50,
      created: "2024-02-19",
    },
    campus: {
      id: 1,
      name: "Test Campus Boys",
      branch: {
        id: 1,
        name: "My Test Branch",
        school: {
          id: 1,
          name: "Testing School",
        },
      },
    },
    applied_grade: {
      id: 1,
      academic_year: {
        id: 1,
        start_year: 2024,
        end_year: 2025,
        status: "Active",
        created: "2024-02-19",
        school: 1,
      },
      department: {
        id: 1,
        name: "Test Primary Boys",
        campus: {
          id: 1,
          name: "Test Campus Boys",
          branch: {
            id: 1,
            name: "My Test Branch",
            school: {
              id: 1,
              name: "Testing School",
            },
          },
        },
      },
      name: "Grade 2",
      level_number: null,
      grading_criteria: null,
      number_of_sections: null,
      created: "2024-02-19",
    },
    parentData: {
      parent_name_arabic: "Ali Irtaza",
      parent_name_english: "Muhammad Sarwar shah",
    },
    studentData: {
      student_national_id: "2343243",
      student_first_name_english: "Ammar",
      student_middle_name_english: "Sarwar",
      student_last_name_english: "shah",
      student_first_name_arabic: "Ammar",
      student_middle_name_arabic: "Sarwar",
      student_last_name_arabic: "shah",
      student_gender: "Female",
      student_date_of_birth: "2002-01-22",
    },
    status: "Active",
    created_at: "2024-03-05",
    student: 12,
  },
];
