export const dummyProgress = [
  {
    id: 15,
    student_first_name_english: "Alaa",
    student_middle_name_english: "Ali",
    student_last_name_english: "Saad",
    student_first_name_arabic: "علاء",
    student_middle_name_arabic: "علي",
    student_last_name_arabic: "سعد",
    parent_name_arabic: "علي",
    parent_name_english: "Ali",
    parent_email: "xxkingmiroxx@gmail.com",
    course: 29,
    progress_report: {
      start_date: "2023-08-27",
      end_date: "2023-08-31",
      comments: null,
      report_data: [
        {
          id: 206,
          progress_type: "Attendance",
          points: 1,
        },
        {
          id: 207,
          progress_type: "Homework",
          points: 2,
        },
        {
          id: 208,
          progress_type: "Punctuality",
          points: 2,
        },
        {
          id: 209,
          progress_type: "Behavior",
          points: 2,
        },
      ],
    },
  },
  {
    id: 16,
    student_first_name_english: "Sami",
    student_middle_name_english: "Ilias",
    student_last_name_english: "Raed",
    student_first_name_arabic: "سامي",
    student_middle_name_arabic: "إلياس",
    student_last_name_arabic: "رائد",
    parent_name_arabic: "إلياس",
    parent_name_english: "Ilias",
    parent_email: "Ilias@gmail.com",
    course: 29,
    progress_report: null,
  },
  {
    id: 17,
    student_first_name_english: "Ammer",
    student_middle_name_english: "Ali",
    student_last_name_english: "Hassan",
    student_first_name_arabic: "عامر",
    student_middle_name_arabic: "علي",
    student_last_name_arabic: "حسن",
    parent_name_arabic: "علي",
    parent_name_english: "Ali",
    parent_email: "xxkingmiroxx@gmail.com",
    course: 29,
    progress_report: null,
  },
];
