export const dummy = [
  {
    id: 3,
    student_first_name_english: "asasas",
    student_middle_name_english: "asasas",
    student_last_name_english: "asasas",
    student_first_name_arabic: "asasas",
    student_middle_name_arabic: "asasas",
    student_last_name_arabic: "asasas",
    parent_name_arabic: "Parent",
    parent_name_english: "New",
    parent_email: "new@parent.com",
    course: 3,
    max_grade: 100,
    quizes: [],
  },
  {
    id: 7,
    student_first_name_english: "New",
    student_middle_name_english: "tes",
    student_last_name_english: "student",
    student_first_name_arabic: "new",
    student_middle_name_arabic: "test",
    student_last_name_arabic: "student",
    parent_name_arabic: "New Parent",
    parent_name_english: "New Parent",
    parent_email: "newparent@test.com",
    course: 3,
    max_grade: 100,
    quizes: [
      {
        id: 1,
        name: "Quarter-2 25",
        total_marks: "25.00",
        weightage: "25.00",
        grade_record: 1,
        obtained_marks: null,
        weighted_marks: null,
      },
      {
        id: 2,
        name: "Quarter-1 25",
        total_marks: "25.00",
        weightage: "25.00",
        grade_record: 2,
        obtained_marks: 22.0,
        weighted_marks: 22.0,
      },
      {
        id: 3,
        name: "Quarter-3 25",
        total_marks: "25.00",
        weightage: "25.00",
        grade_record: 3,
        obtained_marks: null,
        weighted_marks: null,
      },
      {
        id: 4,
        name: "Quarter-4 25",
        total_marks: "25.00",
        weightage: "25.00",
        grade_record: 4,
        obtained_marks: 22.0,
        weighted_marks: null,
      },
    ],
  },
  {
    id: 6,
    student_first_name_english: "New",
    student_middle_name_english: "tes",
    student_last_name_english: "student",
    student_first_name_arabic: "new",
    student_middle_name_arabic: "test",
    student_last_name_arabic: "student",
    parent_name_arabic: "New Parent",
    parent_name_english: "New Parent",
    parent_email: "newparent@test.com",
    course: 3,
    max_grade: 100,
    quizes: [],
  },
];
