export const dummy = [
  {
    id: 2,
    student_first_name_english: "syed",
    student_middle_name_english: "ali",
    student_last_name_english: "irtaza",
    student_first_name_arabic: "syed",
    student_middle_name_arabic: "ali",
    student_last_name_arabic: "irtaza",
    parent_name_arabic: "Muhammad Ali",
    parent_name_english: "Muahmmad Ali",
    parent_email: "hina.saleem@nightingaletech.net",
    attendance: "Absent",
  },
  {
    id: 2,
    student_first_name_english: "Ammar",
    student_middle_name_english: "Sarwar",
    student_last_name_english: "Ali",
    student_first_name_arabic: "Ammar",
    student_middle_name_arabic: "Sarwar",
    student_last_name_arabic: "Ali",
    parent_name_arabic: "Muhammad Ali",
    parent_name_english: "Muahmmad Ali",
    parent_email: "hina.saleem@nightingaletech.net",
    attendance: null,
  },
  {
    id: 6,
    student_first_name_english: "New",
    student_middle_name_english: "tes",
    student_last_name_english: "student",
    student_first_name_arabic: "new",
    student_middle_name_arabic: "test",
    student_last_name_arabic: "student",
    parent_name_arabic: "New Parent",
    parent_name_english: "New Parent",
    parent_email: "newparent@test.com",
    attendance: "Present",
  },
];
